version: '3.8'

services:
  vote-operator:
    build: .
    container_name: vote-operator
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=vote-operator-db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=vote_operator
      - DB_PORT=3306
      - OPERATOR_PRIVATE_KEY=${OPERATOR_PRIVATE_KEY}
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vote-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: vote-operator-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vote_operator
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - vote-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:

networks:
  vote-network:
    driver: bridge
